general.import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 13.0 # Adjust size as needed

[font.normal]
family = "Adwaita Mono Nerd Font"
style = "Regular"

[font.bold]
family = "Adwaita Mono Nerd Font"
style = "Bold"

[font.italic]
family = "Adwaita Mono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Adwaita Mono Nerd Font"
style = "Bold Italic"

[window]
opacity = 0.65
blur = false
padding = { x=16, y=20 }
dynamic_padding = false

